# Use an existing docker image as a base
FROM node:16-alpine

WORKDIR '/app'
COPY package.json .
# Tell the image what to do when it starts as a container
RUN npm install

COPY .  .

CMD ["npm", "run", "start"]